In [ ]:
str2="1/2/3/4/ganesh"
b=[]
for i in str2.split("/"):
  #print(i,end="")
  if i.isdigit():
    b.append(int(i))
  else:
        b.append(i.upper())
  print(b)


[1]
[1, 2]
[1, 2, 3]
[1, 2, 3, 4]
[1, 2, 3, 4, 'GANESH']


In [ ]:
#tuple is immutable data type
t=(1,)

we can pass inside values with user input

In [ ]:
w=tuple(input().split())

79709


In [ ]:
tup=(1,2,3,4)

In [ ]:
tup


(1, 2, 3, 4)

In [ ]:
#python dictionary


In [ ]:
d=set({})

In [ ]:
type(d)

set

In [ ]:
p={20: 'a', 30: 'b'}

In [ ]:
p


{20: 'a', 30: 'b'}

In [ ]:
print(p)

{20: 'a', 30: 'b'}


In [ ]:
def print_even_values(lst):
  try:
     even_values=[x for x in lst if x%2==0]
     print("even values in the list:",even_values)
  except exception as e:
    print("an error occured:",str(e))
my_list=[1,2,3,4,4,5,7]
print_even_values(my_list)

even values in the list: [2, 4, 4]


In [ ]:
#swap of two numbers
a=2
b=3
c=a
a=b
b=c

In [ ]:
a,b

(3, 2)

In [ ]:
a,b=b,a

In [ ]:
print( "a=",a)
print("b=",b)

a= 2
b= 3


In [ ]:
l=[1,2,4,6,7,3,4,6]


In [ ]:
sorted(l)

[1, 2, 3, 4, 4, 6, 6, 7]

In [ ]:
n=len(l)
for i in range(n):
  for j in range(0,n-i-1):
    if l[j]>l[j+1]:
      l[j],l[j+1]=l[j+1],l[j]
print(l)

[1, 2, 3, 4, 4, 6, 6, 7]


In [ ]:
l=[1,4,5,6,7,7,8]
for i in l:
    if i==min(l):
        l.append(i)
        l.remove(i)
l.sort()
print(l)

[1, 4, 5, 6, 7, 7, 8]


In [ ]:
thislist=["apple","mango","grape","cherry","banana","kiwi","melon"]
print(thislist)

['apple', 'mango', 'grape', 'cherry', 'banana', 'kiwi', 'melon']


In [ ]:
print(thislist[1:2])

['mango']


In [ ]:
thislist=["apple","mango","pinapple","cheery"]
if "cheery" in thislist:
  print("yes,'cheery' is in the thislist")
else:
  print("does not exit")

yes,'cheery' is in the thislist


In [ ]:
thislist=["apple","mango","pinapple","cheery"]
thislist[2]="blackcurrent"
print(thislist)

['apple', 'mango', 'blackcurrent', 'cheery']


In [ ]:
thislist=["apple","mango","pinapple","cheery"]
thislist[1:3]=["blacurrent","sapota"]
print(thislist)

['apple', 'blacurrent', 'sapota', 'cheery']


In [ ]:
from numpy import *

In [ ]:
from numpy import arange

In [ ]:
class parent:
  def method(self):
    print("this parent method")
class child(parent):
  def method(self):
    print("this is chid method")
obj1=child()
obj1.method()
#obj2=parent()
#obj2.method()

this is chid method


In [ ]:
class GrandParent:
  def method(self):
    print("this Grandparent method")
class parent(GrandParent):
  def method(self):
    print("this is parent method")
class child(GrandParent):
  def method(self):
     #GrandParent.method(self)
     super().method()
     print("this is chid method")
obj1=child()
obj1.method()
#obj2=parent()
#obj2.method()
#obj3=GrandParent()
#obj3.method()

this Grandparent method
this is chid method


In [ ]:
def one(a):
  print("a+1:",a+1)
def add(num):
  n=5
  return num(n)
add(one)

a+1: 6


In [ ]:
def add(n):
  def one(n):
      return(n+1)
  result=one(n)
  return result
add(9)

10

In [ ]:
def add(n):
   return n+1
def one(fun):
      no=5
      return fun(no)
one(add)

6

In [ ]:
def fun():
  def say():
     return "hi"
  return say
hello=fun()
hello()

'hi'

In [ ]:
def pk(mess):
    "enclosing function"
    def sender():
      "nested function"
    print(mess)
    sender()
print(pk("vote for janasena"))

vote for janasena
None


In [ ]:
def upper_(fun):
  def wrapper():
    func=fun()
    make_=func

@upper_
def hi():
    return "hello"
hi()

In [ ]:
def strip_(fun):
    def wrapper():
         func=fun()
         make_=func.split()
         return make_
    return wrapper

In [ ]:
@strip_
def hi():
  return "hello there vote for janasena party "
hi()

['hello', 'there', 'vote', 'for', 'janasena', 'party']

In [ ]:
def divison(a,b):
  return a/b
print(divison(4,2))

2.0


In [ ]:
def divison_decorater(fun):
  def inner(a,b):
    if b==0:
      return "give proper value except 0"
    return fun(a,b)
  return inner
def div(a,b):
  return a/b
print(div(4,2))

2.0


In [ ]:
@divison_decorater
def div(a,b):
  return a/b
print(div(4,2))

2.0


In [ ]:
#ML(numpy, pandas,matplotlib,seaborn,scipy,plotly,scckit learn,dl9google(tensorflow),facebook(pytorch),mxnet(amazon),microsoft(thenao))

In [ ]:
import numpy

In [ ]:
pip list #!pip list is for jupiter lab

Package                          Version
-------------------------------- ---------------------
absl-py                          1.4.0
aiohttp                          3.8.6
aiosignal                        1.3.1
alabaster                        0.7.13
albumentations                   1.3.1
altair                           4.2.2
anyio                            3.7.1
appdirs                          1.4.4
argon2-cffi                      23.1.0
argon2-cffi-bindings             21.2.0
array-record                     0.4.1
arviz                            0.15.1
astropy                          5.3.4
astunparse                       1.6.3
async-timeout                    4.0.3
attrs                            23.1.0
audioread                        3.0.1
autograd                         1.6.2
Babel                            2.13.0
backcall                         0.2.0
beautifulsoup4                   4.11.2
bleach                           6.1.0
blinker                          1.4
bl

In [ ]:
"""ML
!.how to math using python------------>numpy(numerical python)
2.data handling & data manipulation ---------------->pandas
3.data visualization-------------->matplotlib,seaborn,plotly
4.whenever you use an external packages
  download one time activity
  install (onetime activity)
  import the package in your project (whenever you make a new project you to import it)
  download and install a package in python
  pip install numpy"""

'ML\n!.how to math using python------------>numpy(numerical python)\n2.data handling & data manipulation ---------------->pandas\n3.data visualization-------------->matplotlib,seaborn,plotly\n4.whenever you use an external packages\n  download one time activity\n  install (onetime activity)\n  import the package in your project (whenever you make a new project you to import it)\n  download and install a package in python\n  pip install numpy'

In [ ]:
pip install numpy

In [ ]:
#how to knoe if any package installed or not
!pip show numpy

Name: numpy
Version: 1.23.5
Summary: NumPy is the fundamental package for array computing with Python.
Home-page: https://www.numpy.org
Author: Travis E. Oliphant et al.
Author-email: 
License: BSD
Location: /usr/local/lib/python3.10/dist-packages
Requires: 
Required-by: albumentations, altair, arviz, astropy, autograd, blis, bokeh, bqplot, chex, cmdstanpy, contourpy, cufflinks, cupy-cuda11x, cvxpy, datascience, db-dtypes, dopamine-rl, ecos, flax, folium, geemap, gensim, gym, h5py, holoviews, hyperopt, imageio, imbalanced-learn, imgaug, jax, jaxlib, librosa, lightgbm, matplotlib, matplotlib-venn, missingno, mizani, ml-dtypes, mlxtend, moviepy, music21, nibabel, numba, numexpr, opencv-contrib-python, opencv-python, opencv-python-headless, opt-einsum, optax, orbax-checkpoint, osqp, pandas, pandas-gbq, patsy, plotnine, prophet, pyarrow, pycocotools, pyerfa, pymc, pytensor, python-louvain, PyWavelets, qdldl, qudida, scikit-image, scikit-learn, scipy, scs, seaborn, shapely, sklearn-pandas, 

In [5]:
import numpy as np #np is alias name r surname

In [ ]:
#check the version of package
np.__version__

'1.23.5'

In [ ]:
#for upgrade version
!pip install --upgrade np

  Using cached np-1.0.2-py3-none-any.whl


In [ ]:
#for uninstall package
!pip uninstall np

Found existing installation: np 1.0.2
Uninstalling np-1.0.2:
  Would remove:
    /usr/local/lib/python3.10/dist-packages/np-1.0.2.dist-info/*
    /usr/local/lib/python3.10/dist-packages/np/*
Proceed (Y/n)? y
  Successfully uninstalled np-1.0.2


In [ ]:
#math
list1=[1,2,3,4]#list hetergeneous data type
#expetced o/p=[2,4,6,8]

In [ ]:
l2=[]
for i in list1:
    l2.append(i*2)
print(l2)

[2, 4, 6, 8]


In [ ]:
list1*2

[1, 2, 3, 4, 1, 2, 3, 4]

In [ ]:
import array as ar

In [ ]:
r=ar

In [ ]:
dir(np)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'VisibleDeprecationWarning',
 'WRAP',
 '_CopyMode',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__deprecated_attrs__',
 '__dir__',
 '__doc__',
 '__expired_functions__',
 '__file__',
 '__getattr__',
 '__git_version__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 

In [ ]:
list1

[1, 2, 3, 4]

#convert a list to np array

In [ ]:
ar=np.array(list1)

In [ ]:
print(ar)

[1 2 3 4]


In [ ]:
print(type(ar))

<class 'numpy.ndarray'>


In [ ]:
#nd array means n dimwnsional array
ar
#expected output is [2,4,6,8]

array([1, 2, 3, 4])

In [ ]:
ar*2

array([2, 4, 6, 8])

In [ ]:
ar

array([1, 2, 3, 4])

#2 . zeros in my array

In [ ]:
np.zeros(10,dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

#ones in my arr

In [ ]:
np.ones(10,dtype=int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

if you want print all 2's r 3,4,5,6,7,8,9, like this we have to mulyiply

In [ ]:
np.ones(10,dtype=int)*5

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

if you want to print float we have give float in placee of int

In [ ]:
np.ones(10,dtype=float)*5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [ ]:
#guru mantrs any function
?np.zeros

In [ ]:
#ke an array with 4's 7coloumns and 5 rows

In [ ]:
ar=np.zeros((5,7),dtype=int)+4

In [ ]:
ar

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

we can not add direcly to a list

In [ ]:
list=[1,2,3,4,5]+6

TypeError: ignored

In [ ]:
#4 how to find shape of an array

In [ ]:
ar.shape

(5, 7)

to find out dimension (ndim) is used

In [ ]:
ar.ndim

2

In [ ]:
ar.itemsize

8

In [ ]:
ar.size

35

In [ ]:
ar1=np.ones((5,7,6),dtype=int)

here 5 is total of matarix and 7 is colum and 6 is rows

In [ ]:
ar1

array([[[1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1]]])

In [ ]:
ar1.dtype

dtype('int64')

In [ ]:
ar1.ndim

In [ ]:
ar1.itemsize

In [ ]:
ar2=np.random.randint(10,50,(3,2))

In [ ]:
ar2

In [ ]:
ar2

In [ ]:
ar2m

In [ ]:
ar3=np.random.seed(42)

In [ ]:
np.random.seed(30)

In [ ]:
ar4=np.random.randint(10,50,(3,4))

In [ ]:
print(ar4)

In [ ]:
print(ar4)

In [ ]:
#decimal random numbers
np.random.rand(6,4)

In [ ]:
ar6=np.random.rand(2,3,4)

In [ ]:
print(ar6)

In [ ]:
ar6.ndim

In [ ]:
ar5=np.array([1,2,3,4,5,6,7,8,9])

In [ ]:
ar8=ar5.reshape(9,1)

In [ ]:
print(ar8)

In [ ]:
ar8=np.std(ar8)

In [ ]:
ar8.sum()

In [ ]:
ar8

In [ ]:
ar8.mean()


In [ ]:
ar8.std()

In [ ]:
np.eye(3,dtype=int,k=1)

In [ ]:
np.identity(4,dtype=bool)

In [ ]:
#numpy is mutable data type
#indexing and slicing


In [ ]:
ar12=np.random.randint(0,10,(3,3))

In [ ]:
ar12

array([[3, 9, 6],
       [5, 0, 6],
       [5, 3, 7]])

In [ ]:
ar12[0]

array([3, 5, 7])

In [ ]:
ar12[1,2]

4

In [ ]:
ar12[1:3,0:2]

array([[5, 0],
       [5, 3]])

In [ ]:
#slicing
ar12[0:1,1:2]

array([[9]])

In [ ]:
ar12[1:2,0:2]

array([[5, 0]])

In [ ]:
ar9=np.random.randint(1,20,(3,3))

In [ ]:
ar9

array([[ 8, 13,  7],
       [12, 12,  6],
       [12,  4,  7]])

In [ ]:
ar9[:,:]

array([[ 8, 13,  7],
       [12, 12,  6],
       [12,  4,  7]])

In [ ]:
ar9[]

array([[12, 12,  6],
       [12,  4,  7]])

In [ ]:
ar9[1:3:1,1:3:1]

array([[12,  6],
       [ 4,  7]])

In [ ]:
ar9[0:2:1,0:2:1]

array([[ 8, 13],
       [12, 12]])

In [ ]:
ar9[0::2,0::2 ]

array([[ 8,  7],
       [12,  7]])

In [19]:
ar10=np.random.seed(42)
ar10=np.random.randint(1,10,(5,7))

In [17]:
ar10

array([[2, 4, 9, 2, 9, 5, 2],
       [4, 7, 8, 3, 1, 4, 2],
       [8, 4, 2, 6, 6, 4, 6],
       [2, 2, 4, 8, 7, 9, 8],
       [5, 2, 5, 8, 9, 9, 1]])

In [9]:
ar10[1:4:1,0:6:]

array([[1, 2, 4, 8, 5, 8],
       [2, 7, 1, 7, 1, 5],
       [9, 9, 5, 6, 5, 2]])